import { z } from "zod";
import {
  PASSWORD_DIGIT_MESSAGE,
  PASSWORD_LENGTH_MESSAGE,
  PASSWORD_LOWERCASE_MESSAGE,
  PASSWORD_MAX_LENGTH,
  PASSWORD_MIN_LENGTH,
  PASSWORD_SPECIAL_CHAR_MESSAGE,
  PASSWORD_UPPERCASE_MESSAGE,
} from "../constants/auth.constants";

export const passwordSchema = z
  .string()
  .min(PASSWORD_MIN_LENGTH, PASSWORD_LENGTH_MESSAGE)
  .max(PASSWORD_MAX_LENGTH, PASSWORD_LENGTH_MESSAGE)
  .regex(/[A-Z]/, PASSWORD_UPPERCASE_MESSAGE)
  .regex(/[a-z]/, PASSWORD_LOWERCASE_MESSAGE)
  .regex(/\d/, PASSWORD_DIGIT_MESSAGE)
  .regex(/[^\w\s]/, PASSWORD_SPECIAL_CHAR_MESSAGE);
