import { productImage, productGallery, type ProductSeed } from "../helpers";

export const menClothingProducts: ProductSeed[] = [
  // ═══════════════════════════════════════════════════════
  // T-Shirts
  // ═══════════════════════════════════════════════════════
  {
    name: "Classic Cotton T-Shirt",
    arName: "تيشيرت قطن كلاسيك",
    slug: "classic-cotton-tshirt",
    sku: "MEN-TS-001",
    regularPrice: 29.99,
    discountPrice: 19.99,
    onDiscount: true,
    discountType: "FIXED",
    discountValue: 10,
    description: "100% cotton premium T-shirt. Comfortable and durable.",
    arDescription: "تيشيرت قطن 100% فاخر. مريح ومتين.",
    mainImage: productImage("men-ts-classic"),
    imageGallery: productGallery("men-ts-classic", 2),
    categorySlugs: ["men-tshirts"],
    variants: [
      {
        sku: "MEN-TS-001-S",
        name: "Small - White",
        arName: "صغير - أبيض",
        size: "S",
        attributes: { color: "white" },
        stockQuantity: 30,
      },
      {
        sku: "MEN-TS-001-M",
        name: "Medium - White",
        arName: "متوسط - أبيض",
        size: "M",
        attributes: { color: "white" },
        stockQuantity: 40,
      },
      {
        sku: "MEN-TS-001-L",
        name: "Large - White",
        arName: "كبير - أبيض",
        size: "L",
        attributes: { color: "white" },
        stockQuantity: 25,
      },
      {
        sku: "MEN-TS-001-XL",
        name: "X-Large - White",
        arName: "كبير جداً - أبيض",
        size: "XL",
        attributes: { color: "white" },
        stockQuantity: 15,
      },
    ],
  },
  {
    name: "Graphic Print T-Shirt",
    arName: "تيشيرت بطبعة جرافيك",
    slug: "graphic-tshirt",
    sku: "MEN-TS-GRF",
    regularPrice: 34.99,
    discountPrice: 34.99,
    description: "Stylish graphic print T-shirt.",
    arDescription: "تيشيرت بطبعة جرافيك أنيقة.",
    mainImage: productImage("men-ts-graphic"),
    imageGallery: productGallery("men-ts-graphic", 2),
    categorySlugs: ["men-tshirts"],
    variants: [
      {
        sku: "MEN-TS-GRF-BLK",
        name: "Black - M",
        arName: "أسود - متوسط",
        size: "M",
        attributes: { color: "black" },
        stockQuantity: 20,
      },
      {
        sku: "MEN-TS-GRF-NVY",
        name: "Navy - L",
        arName: "كحلي - كبير",
        size: "L",
        attributes: { color: "navy" },
        stockQuantity: 18,
      },
    ],
  },

  // ═══════════════════════════════════════════════════════
  // Jeans
  // ═══════════════════════════════════════════════════════
  {
    name: "Slim Fit Blue Jeans",
    arName: "بنطلون جينز سليم فيت أزرق",
    slug: "slim-fit-blue-jeans",
    sku: "MEN-JN-SLIM",
    regularPrice: 79.99,
    discountPrice: 59.99,
    onDiscount: true,
    discountType: "FIXED",
    discountValue: 20,
    description: "Premium slim-fit jeans with stretch fabric.",
    arDescription: "جينز سليم فيت فاخر بقماش مطاطي.",
    mainImage: productImage("men-jeans-slim"),
    imageGallery: productGallery("men-jeans-slim", 2),
    categorySlugs: ["men-jeans"],
    variants: [
      {
        sku: "MEN-JN-SLIM-30",
        name: "Size 30",
        arName: "مقاس 30",
        size: "30",
        attributes: { waist: "30", color: "blue" },
        stockQuantity: 15,
      },
      {
        sku: "MEN-JN-SLIM-32",
        name: "Size 32",
        arName: "مقاس 32",
        size: "32",
        attributes: { waist: "32", color: "blue" },
        stockQuantity: 22,
      },
      {
        sku: "MEN-JN-SLIM-34",
        name: "Size 34",
        arName: "مقاس 34",
        size: "34",
        attributes: { waist: "34", color: "blue" },
        stockQuantity: 18,
      },
      {
        sku: "MEN-JN-SLIM-36",
        name: "Size 36",
        arName: "مقاس 36",
        size: "36",
        attributes: { waist: "36", color: "blue" },
        stockQuantity: 10,
      },
    ],
  },
  {
    name: "Black Skinny Jeans",
    arName: "بنطلون جينز سكيني أسود",
    slug: "black-skinny-jeans",
    sku: "MEN-JN-BLK",
    regularPrice: 69.99,
    discountPrice: 69.99,
    description: "Stylish skinny-fit black jeans.",
    arDescription: "جينز سكيني أسود أنيق.",
    mainImage: productImage("men-jeans-black"),
    imageGallery: productGallery("men-jeans-black", 2),
    categorySlugs: ["men-jeans"],
  },

  // ═══════════════════════════════════════════════════════
  // Underwear
  // ═══════════════════════════════════════════════════════
  {
    name: "Cotton Boxer Briefs - 3 Pack",
    arName: "بوكسرات قطن - 3 حبات",
    slug: "cotton-boxer-briefs-3pack",
    sku: "MEN-UW-3PK",
    regularPrice: 34.99,
    discountPrice: 24.99,
    onDiscount: true,
    discountType: "FIXED",
    discountValue: 10,
    description: "Pack of 3 premium cotton boxer briefs.",
    arDescription: "3 بوكسرات قطن فاخرة.",
    mainImage: productImage("men-underwear-boxers"),
    imageGallery: productGallery("men-underwear-boxers", 2),
    categorySlugs: ["men-underwear"],
    variants: [
      {
        sku: "MEN-UW-3PK-S",
        name: "Small",
        arName: "صغير",
        size: "S",
        attributes: { color: "assorted" },
        stockQuantity: 25,
      },
      {
        sku: "MEN-UW-3PK-M",
        name: "Medium",
        arName: "متوسط",
        size: "M",
        attributes: { color: "assorted" },
        stockQuantity: 40,
      },
      {
        sku: "MEN-UW-3PK-L",
        name: "Large",
        arName: "كبير",
        size: "L",
        attributes: { color: "assorted" },
        stockQuantity: 30,
      },
    ],
  },

  // ═══════════════════════════════════════════════════════
  // Shorts
  // ═══════════════════════════════════════════════════════
  {
    name: "Athletic Sport Shorts",
    arName: "شورت رياضي",
    slug: "athletic-sport-shorts",
    sku: "MEN-SH-ATH",
    regularPrice: 39.99,
    discountPrice: 29.99,
    onDiscount: true,
    discountType: "FIXED",
    discountValue: 10,
    description: "Lightweight athletic shorts for training.",
    arDescription: "شورت رياضي خفيف للتمرين.",
    mainImage: productImage("men-shorts-ath"),
    imageGallery: productGallery("men-shorts-ath", 2),
    categorySlugs: ["men-shorts"],
    variants: [
      {
        sku: "MEN-SH-ATH-BLK-M",
        name: "Black - M",
        arName: "أسود - متوسط",
        size: "M",
        attributes: { color: "black" },
        stockQuantity: 22,
      },
      {
        sku: "MEN-SH-ATH-BLK-L",
        name: "Black - L",
        arName: "أسود - كبير",
        size: "L",
        attributes: { color: "black" },
        stockQuantity: 18,
      },
    ],
  },
];
