import { productImage, productGallery, type ProductSeed } from "../helpers";

export const womenClothingProducts: ProductSeed[] = [
  {
    name: "Floral Summer Dress",
    arName: "فستان صيفي بالزهور",
    slug: "floral-summer-dress",
    sku: "WOM-DR-FLR",
    regularPrice: 89.99,
    discountPrice: 69.99,
    onDiscount: true,
    discountType: "FIXED",
    discountValue: 20,
    description: "Beautiful floral summer dress.",
    arDescription: "فستان صيفي جميل بالزهور.",
    mainImage: productImage("women-dress-floral"),
    imageGallery: productGallery("women-dress-floral", 3),
    isNew: true,
    categorySlugs: ["women-dresses"],
    variants: [
      {
        sku: "WOM-DR-FLR-S",
        name: "Small",
        arName: "صغير",
        size: "S",
        attributes: { color: "floral" },
        stockQuantity: 12,
      },
      {
        sku: "WOM-DR-FLR-M",
        name: "Medium",
        arName: "متوسط",
        size: "M",
        attributes: { color: "floral" },
        stockQuantity: 15,
      },
      {
        sku: "WOM-DR-FLR-L",
        name: "Large",
        arName: "كبير",
        size: "L",
        attributes: { color: "floral" },
        stockQuantity: 8,
      },
    ],
  },
  {
    name: "Women's White T-Shirt",
    arName: "تيشيرت نسائي أبيض",
    slug: "women-white-tshirt",
    sku: "WOM-TS-WHT",
    regularPrice: 24.99,
    discountPrice: 19.99,
    onDiscount: true,
    discountType: "FIXED",
    discountValue: 5,
    description: "Basic white T-shirt for women.",
    arDescription: "تيشيرت نسائي أبيض أساسي.",
    mainImage: productImage("women-ts-white"),
    imageGallery: productGallery("women-ts-white", 2),
    categorySlugs: ["women-tshirts"],
    variants: [
      {
        sku: "WOM-TS-WHT-S",
        name: "Small",
        arName: "صغير",
        size: "S",
        attributes: { color: "white" },
        stockQuantity: 25,
      },
      {
        sku: "WOM-TS-WHT-M",
        name: "Medium",
        arName: "متوسط",
        size: "M",
        attributes: { color: "white" },
        stockQuantity: 30,
      },
      {
        sku: "WOM-TS-WHT-L",
        name: "Large",
        arName: "كبير",
        size: "L",
        attributes: { color: "white" },
        stockQuantity: 20,
      },
    ],
  },
  {
    name: "Leather Handbag",
    arName: "حقيبة يد جلد",
    slug: "leather-handbag",
    sku: "WOM-BG-LTH",
    regularPrice: 199.99,
    discountPrice: 159.99,
    onDiscount: true,
    discountType: "FIXED",
    discountValue: 40,
    description: "Elegant leather handbag with adjustable strap.",
    arDescription: "حقيبة يد جلد أنيقة بحزام قابل للتعديل.",
    mainImage: productImage("women-handbag"),
    imageGallery: productGallery("women-handbag", 3),
    isNew: true,
    categorySlugs: ["women-bags"],
    variants: [
      {
        sku: "WOM-BG-LTH-BRN",
        name: "Brown",
        arName: "بني",
        attributes: { color: "brown" },
        stockQuantity: 15,
      },
      {
        sku: "WOM-BG-LTH-BLK",
        name: "Black",
        arName: "أسود",
        attributes: { color: "black" },
        stockQuantity: 20,
      },
      {
        sku: "WOM-BG-LTH-BGE",
        name: "Beige",
        arName: "بيج",
        attributes: { color: "beige" },
        stockQuantity: 10,
      },
    ],
  },
];
