import { z } from "zod";
import {
  PASSWORD_DIGIT_MSG,
  PASSWORD_LENGTH_MSG,
  PASSWORD_LOWERCASE_MSG,
  PASSWORD_MAX_LENGTH,
  PASSWORD_MIN_LENGTH,
  PASSWORD_MUST_CONTAIN_DIGITS,
  PASSWORD_MUST_CONTAIN_LOWERCASE,
  PASSWORD_MUST_CONTAIN_SPECIAL_CHARS,
  PASSWORD_MUST_CONTAIN_UPPERCASE,
  PASSWORD_MUST_NOT_CONTAIN_EQUAL,
  PASSWORD_MUST_NOT_CONTAIN_EQUAL_MSG,
  PASSWORD_MUST_NOT_CONTAIN_WHITESPACE,
  PASSWORD_MUST_NOT_CONTAIN_WHITESPACE_MSG,
  PASSWORD_SPECIAL_CHAR_MSG,
  PASSWORD_UPPERCASE_MSG,
} from "../../../constants";

export const passwordSchema = z
  .string()
  .min(PASSWORD_MIN_LENGTH, PASSWORD_LENGTH_MSG)
  .max(PASSWORD_MAX_LENGTH, PASSWORD_LENGTH_MSG)
  .regex(PASSWORD_MUST_CONTAIN_UPPERCASE, PASSWORD_UPPERCASE_MSG)
  .regex(PASSWORD_MUST_CONTAIN_LOWERCASE, PASSWORD_LOWERCASE_MSG)
  .regex(PASSWORD_MUST_CONTAIN_DIGITS, PASSWORD_DIGIT_MSG)
  .regex(PASSWORD_MUST_CONTAIN_SPECIAL_CHARS, PASSWORD_SPECIAL_CHAR_MSG)
  .regex(
    PASSWORD_MUST_NOT_CONTAIN_WHITESPACE,
    PASSWORD_MUST_NOT_CONTAIN_WHITESPACE_MSG,
  )
  .regex(PASSWORD_MUST_NOT_CONTAIN_EQUAL, PASSWORD_MUST_NOT_CONTAIN_EQUAL_MSG);
