import { z } from "zod";
import {
  USERNAME_LENGTH_MSG,
  USERNAME_MAX_LENGTH,
  USERNAME_MSG,
  USERNAME_MIN_LENGTH,
  USERNAME_REGEX,
  USERNAME_MUST_NOT_CONTAIN_EQUAL_MSG,
  USERNAME_MUST_NOT_CONTAIN_EQUAL,
} from "../../../constants";

export const usernameSchema = z
  .string()
  .trim()
  .min(USERNAME_MIN_LENGTH, USERNAME_LENGTH_MSG)
  .max(USERNAME_MAX_LENGTH, USERNAME_LENGTH_MSG)
  .regex(USERNAME_REGEX, USERNAME_MSG)
  .regex(USERNAME_MUST_NOT_CONTAIN_EQUAL, USERNAME_MUST_NOT_CONTAIN_EQUAL_MSG);
