export * from "./list-products.swagger";
export * from "./get-product.swagger";
export * from "./get-product-by-slug.swagger";
export * from "./get-product-categories.swagger";
export * from "./get-product-categories-by-slug.swagger";
export * from "./create-product.swagger";
export * from "./bulk-create-products.swagger";
export * from "./update-product.swagger";
export * from "./delete-product.swagger";
